name: Bug report
description: Template used to report bugs
title: --/BR-XXX - Descriptive title
labels: bug
body:
  - type: textarea
    id: problem-to-solve
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: What happened!
    validations:
      required: true
  - type: dropdown
    id: OS
    attributes:
      label: Device OS
      description: On which operating system did you experience this problem?
      options:
        - Android
        - iOS
      default: 0
    validations:
      required: true
  - type: dropdown
    id: android-versions
    attributes:
      label: Android Version
      description: If your device is android, select a version.
      multiple: true
      options:
        - 13
        - 12
        - 11
        - 10
        - 9 (Pie)
        - 8 (Oreo)
    validations:
      required: true
  - type: dropdown
    id: ios-versions
    attributes:
      label: iOS Version
      description: If your device is iOS, select a version.
      multiple: true
      options:
        - 17
        - 16
        - 15
        - 14
        - 13
        - 12
    validations:
      required: true
